name: Build SumatraPDF (DN-fork)

on:
  workflow_dispatch:
  push:
    branches: [ "dn_3.5.2_patch2" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive # 依存関係の取得に必須です

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2 # これで msbuild コマンドを有効化します

    - name: Build SumatraPDF
      run: |
        msbuild vs2022/SumatraPDF.sln `
          -property:Configuration=Release `
          -property:Platform=x64 `
          -maxCpuCount

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SumatraPDF-DN-fork-exe
        path: |
          **/SumatraPDF.exe
          **/SumatraPDF.dll
          **/libmupdf.dll
